verboser logging

diff --git a/bin/get_ec2_ip b/bin/get_ec2_ip
--- a/bin/get_ec2_ip
+++ b/bin/get_ec2_ip
@@ -5,7 +5,7 @@ set -o pipefail
 set -o errexit
 set -o nounset
 
-ec2_script="$(dirname $(realpath $0) )/ec2"
+ec2_script="$(dirname $(realpath $0))/ec2"
 
 if [[ "$#" -ge 1 ]] && [[ "$1" =~ ^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$ ]];then
   instance_ip="$1"
@@ -28,6 +28,7 @@ else
 fi
 
 if [[ -z "$instance_ip" ]];then
+  echo "cannot determine instance ip from : $1" >&2
   exit 1
 fi
 echo "$instance_ip"
