added tracing and fixed bug when names are similar

diff --git a/bin/lib/get_ec2_id b/bin/lib/get_ec2_id
--- a/bin/lib/get_ec2_id
+++ b/bin/lib/get_ec2_id
@@ -18,7 +18,7 @@ elif [[ "$#" -ge 1 ]] && [[ "$1" =~ ^i-[0-9a-f]*$ ]];then
 
 elif [[ "$#" -ge 1 ]];then
   instance_id="$($ec2_script -l list \
-    | jq -r "map(select(.Tags//[]|contains([{Key:\"Name\",Value:\"$1\"}])))\
+    | jq -r "map(select(.Tags//[]|inside([{Key:\"Name\",Value:\"$1\"}])))\
             |.[0].InstanceId"
   )"
 
@@ -29,7 +29,7 @@ else
 fi
 
 if [[ -z "$instance_id" ]];then
-  echo "cannot determine instance ip from : $@" >&2
+  echo "cannot determine instance id from : $@" >&2
   exit 1
 fi
 echo "$instance_id"
